### PR TITLE
Search for acegisecurity package

### PR DESCRIPTION
**Pull request by Wadeck**
Not meant to be merged, but kept as an example of custom usage.

Provide an updated version of https://issues.jenkins-ci.org/browse/JENKINS-5303 comment from Daniel (from 2018).

<details>

<summary>Output for "usage-by-api"</summary>

### org/acegisecurity/AccessDeniedException
authorize-project
blueocean-rest-impl
branch-api
build-failure-analyzer
build-pipeline-plugin
build-token-root
categorized-view
cloudbees-folder
credentials
depgraph-view
deployment-sphere
docker-slaves
docker-traceability
DotCi
dry-run
favorite-view
hp-application-automation-tools-plugin
ivy
jenkins-multijob-plugin
jobConfigHistory
jobtemplates
junit
mac
matrix-project
maven-plugin
metrics
next-build-number
node-sharing-orchestrator
ownership
parameterized-trigger
periodicbackup
pipeline-maven
pipeline-model-definition
pipeline-restful-api
plugin-util-api
project-inheritance
promoted-builds
pubsub-light
purge-job-history
reqtify
scm-sync-configuration
slave-squatter
svnmerge
usemango-runner
workflow-cps
workflow-durable-task-step
### org/acegisecurity/AccountExpiredException
crowd2
### org/acegisecurity/AcegiMessageSource
reverse-proxy-auth-plugin
### org/acegisecurity/AcegiSecurityException
active-directory
ldap
### org/acegisecurity/acls/NotFoundException
artifactory
### org/acegisecurity/acls/sid/PrincipalSid
folder-auth
role-strategy
ssh2easy
### org/acegisecurity/acls/sid/Sid
folder-auth
matrix-auth
role-strategy
ssh2easy
### org/acegisecurity/Authentication
active-directory
alauda-devops-credentials-provider
amazon-ecr
artifactory
assembla-auth
atlassian-bitbucket-server-integration
authorize-project
aws-secrets-manager-credentials-provider
azure-ad
azure-keyvault
batch-task
bitbucket-oauth
block-same-builds
blueocean-jwt
blueocean-pipeline-api-impl
blueocean-pipeline-scm-api
blueocean-rest-impl
branch-api
build-failure-analyzer
cas-plugin
claim
cloudbees-folder
coding-webhook
compound-slaves
concurrent-login-plugin
copyartifact
createjobadvanced
credentials
crowd2
deployer-framework
distfork
docker-slaves
DotCi
favorite
gerrit-code-review
gerrit-trigger
git-server
github-oauth
gitlab-oauth
google-container-registry-auth
google-login
google-source-plugin
greenballs
hp-application-automation-tools-plugin
ibm-continuous-release
instant-messaging
jira-steps
job-fan-in
jobConfigHistory
jwt-support
kerberos-sso
keycloak
kubernetes
kubernetes-credentials-provider
ldap
m2release
matrix-auth
microdocs-integration
monitoring
NegotiateSSO
nodejs
oic-auth
openid
openshift-login
openstack-cloud
ownership
package-drone
parameterized-trigger
pipeline-input-step
pipeline-maven
project-inheritance
promoted-builds
pubsub-light
pwauth
remote-terminal-access
reverse-proxy-auth-plugin
saml
script-security
scriptler
shelve-project-plugin
skype-notifier
splunk-devops
sse-gateway
ssh-steps
ssh2easy
stashNotifier
statistics-gatherer
strict-crumb-issuer
sumologic-publisher
support-core
team-views
teamconcert-git
thinBackup
tuleap-oauth
typetalk
urbancode-velocity
url-auth-sso
view-job-filters
windows-azure-storage
workflow-api
workflow-cps
workflow-durable-task-step
workflow-job
workflow-multibranch
workflow-step-api
wso2id-oauth
wwpass-plugin
### org/acegisecurity/AuthenticationException
active-directory
assembla-auth
azure-ad
backlog
bitbucket-oauth
cas-plugin
coding-webhook
crowd2
delivery-pipeline-plugin
github-oauth
gitlab-oauth
google-login
ibm-continuous-release
job-restrictions
keycloak
ldap
matrix-auth
mock-security-realm
oic-auth
openid
openshift-login
pam-auth
pwauth
redmine
reverse-proxy-auth-plugin
saml
script-realm
skype-notifier
tuleap-oauth
urbancode-velocity
url-auth-sso
wso2id-oauth
wwpass-plugin
### org/acegisecurity/AuthenticationManager
assembla-auth
authorize-project
azure-ad
bitbucket-oauth
cas-plugin
coding-webhook
crowd2
DotCi
github-oauth
gitlab-oauth
google-login
ibm-continuous-release
keycloak
ldap
oic-auth
openshift-login
pwauth
saml
skype-notifier
tuleap-oauth
urbancode-velocity
url-auth-sso
wso2id-oauth
wwpass-plugin
### org/acegisecurity/AuthenticationServiceException
active-directory
cas-plugin
crowd2
ldap
reverse-proxy-auth-plugin
script-realm
### org/acegisecurity/BadCredentialsException
active-directory
assembla-auth
azure-ad
backlog
bitbucket-oauth
cas-plugin
coding-webhook
crowd2
delivery-pipeline-plugin
github-oauth
gitlab-oauth
google-login
keycloak
ldap
mock-security-realm
oic-auth
openid
openshift-login
pam-auth
pwauth
reverse-proxy-auth-plugin
role-strategy
saml
script-realm
tuleap-oauth
wso2id-oauth
wwpass-plugin
### org/acegisecurity/context/SecurityContext
assembla-auth
azure-ad
backup
bitbucket-oauth
blueocean-jwt
cas-plugin
coding-webhook
crowd2
DotCi
elasticbox
extended-choice-parameter
ghprb
gitbucket
github-oauth
gitlab-oauth
google-login
ibm-continuous-release
jclouds-jenkins
jwt-support
kerberos-sso
keycloak
NegotiateSSO
oic-auth
openid
openshift-login
periodicbackup
promoted-builds
reverse-proxy-auth-plugin
saml
subversion
teamconcert-git
thinBackup
tuleap-oauth
urbancode-velocity
url-auth-sso
wso2id-oauth
wwpass-plugin
xpdev
### org/acegisecurity/context/SecurityContextHolder
alauda-devops-sync
assembla-auth
azure-ad
backlog
backup
bitbucket
bitbucket-oauth
blueocean-bitbucket-pipeline
blueocean-github-pipeline
blueocean-jwt
build-token-root
buildresult-trigger
cas-plugin
coding-webhook
credentials
crowd2
deploydb
docker-slaves
dockerhub-notification
DotCi
elasticbox
embeddable-build-status
extended-choice-parameter
feature-branch-notifier
gearman-plugin
generic-webhook-trigger
gerrit-code-review
ghprb
gitbucket
github-oauth
github-pullrequest
gitlab-oauth
gogs-webhook
google-login
ibm-continuous-release
jclouds-jenkins
job-fan-in
jobcopy-builder
jwt-support
kerberos-sso
keycloak
metrics
multibranch-scan-webhook-trigger
NegotiateSSO
oic-auth
openid
openshift-login
openshift-sync
ownership
periodicbackup
PrioritySorter
project-inheritance
promoted-builds
rabbitmq-consumer
random-job-builder
reverse-proxy-auth-plugin
saml
scm-api
script-security
security-inspector
seed
subversion
teamconcert-git
tfs
thinBackup
throttle-concurrents
tuleap-oauth
urbancode-velocity
url-auth-sso
windows-azure-storage
wso2id-oauth
wwpass-plugin
xpdev
zanata
### org/acegisecurity/context/SecurityContextImpl
blueocean-jwt
jwt-support
### org/acegisecurity/CredentialsExpiredException
crowd2
### org/acegisecurity/DisabledException
cas-plugin
### org/acegisecurity/GrantedAuthority
active-directory
assembla-auth
azure-ad
bitbucket-oauth
blueocean-jwt
cas-plugin
coding-webhook
crowd2
github-oauth
gitlab-oauth
job-restrictions
jwt-support
keycloak
ldap
oic-auth
openid
openshift-login
pam-auth
pipeline-input-step
promoted-builds
redmine
reverse-proxy-auth-plugin
role-strategy
saml
script-realm
tuleap-oauth
url-auth-sso
wso2id-oauth
wwpass-plugin
### org/acegisecurity/GrantedAuthorityImpl
active-directory
assembla-auth
azure-ad
bitbucket-oauth
cas-plugin
crowd2
github-oauth
gitlab-oauth
keycloak
ldap
mock-security-realm
oic-auth
openid
pam-auth
pwauth
reverse-proxy-auth-plugin
script-realm
tuleap-oauth
### org/acegisecurity/InsufficientAuthenticationException
crowd2
### org/acegisecurity/ldap/InitialDirContextFactory
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/ldap/LdapCallback
ldap
### org/acegisecurity/ldap/LdapDataAccessException
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/ldap/LdapEntryMapper
ldap
### org/acegisecurity/ldap/LdapTemplate
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/ldap/LdapUserSearch
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/LockedException
cas-plugin
### org/acegisecurity/providers/AbstractAuthenticationToken
assembla-auth
bitbucket-oauth
blueocean-jwt
cas-plugin
coding-webhook
crowd2
github-oauth
gitlab-oauth
jwt-support
keycloak
saml
tuleap-oauth
url-auth-sso
wso2id-oauth
wwpass-plugin
### org/acegisecurity/providers/dao/AbstractUserDetailsAuthenticationProvider
active-directory
redmine
reverse-proxy-auth-plugin
### org/acegisecurity/providers/ldap/LdapAuthenticationProvider
ldap
### org/acegisecurity/providers/ldap/LdapAuthenticator
ldap
### org/acegisecurity/providers/ldap/LdapAuthoritiesPopulator
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/providers/ldap/populator/DefaultLdapAuthoritiesPopulator
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/providers/UsernamePasswordAuthenticationToken
active-directory
authorize-project
cas-plugin
coding-webhook
copyartifact
credentials
github-oauth
gitlab-oauth
google-login
hp-application-automation-tools-plugin
ibm-continuous-release
kerberos-sso
ldap
NegotiateSSO
oic-auth
openid
openshift-login
perfectomobile
pwauth
redmine
reverse-proxy-auth-plugin
s3
skype-notifier
urbancode-velocity
wso2id-oauth
### org/acegisecurity/ui/rememberme/RememberMeServices
crowd2
### org/acegisecurity/userdetails/ldap/LdapUserDetails
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/userdetails/ldap/LdapUserDetailsImpl$Essence
ldap
reverse-proxy-auth-plugin
### org/acegisecurity/userdetails/User
active-directory
assembla-auth
backlog
cas-plugin
coding-webhook
github-oauth
gitlab-oauth
keycloak
mock-security-realm
openid
pam-auth
pwauth
script-realm
url-auth-sso
wso2id-oauth
### org/acegisecurity/userdetails/UserDetails
active-directory
assembla-auth
azure-ad
backlog
bitbucket-oauth
blueocean-jwt
cas-plugin
coding-webhook
crowd2
datadog
github-oauth
gitlab-oauth
ibm-continuous-release
job-restrictions
jwt-support
kerberos-sso
ldap
mock-security-realm
NegotiateSSO
oic-auth
openshift-login
pam-auth
pwauth
redmine
reverse-proxy-auth-plugin
role-strategy
saml
script-realm
splunk-devops
sumologic-publisher
tuleap-oauth
urbancode-velocity
url-auth-sso
wso2id-oauth
wwpass-plugin
### org/acegisecurity/userdetails/UserDetailsService
active-directory
assembla-auth
azure-ad
bitbucket-oauth
coding-webhook
crowd
crowd2
github-oauth
gitlab-oauth
ldap
oic-auth
pwauth
reverse-proxy-auth-plugin
saml
url-auth-sso
wso2id-oauth
### org/acegisecurity/userdetails/UsernameNotFoundException
active-directory
assembla-auth
authorize-project
azure-ad
backlog
bitbucket-oauth
blueocean-pipeline-scm-api
coding-webhook
credentials
crowd
crowd2
email-ext
github-oauth
gitlab-oauth
hp-application-automation-tools-plugin
job-restrictions
kerberos-sso
ldap
mailer
matrix-auth
mock-security-realm
oic-auth
ownership
pam-auth
pwauth
redmine
restricted-register
reverse-proxy-auth-plugin
saml
script-realm
security-inspector
tuleap-oauth
urbancode-velocity
url-auth-sso
workflow-cps
wso2id-oauth
wwpass-plugin

</details>

### CODE REVIEW

**Comment by jglick** [comment]
conflicts with #14 BTW

**Comment by jglick** [comment]
I do not think you need to patch anything. After

```bash
mvn -f jenkinsci/jenkins -pl core dependency:tree | perl -n -e 'if (/([^ ]+):((spring|acegi).+):jar:(.+):compile/) {my $g = $1; $g =~ tr!.!/!; print("$ENV{HOME}/.m2/repository/$g/$2/$4/$2-$4.jar\n")}' | xargs -n1 jar tf | fgrep .class | sed -e 's/.class$//' | sort | uniq > /tmp/additionalClasses
```

you can run this tool with

```
--additionalClasses /tmp/additionalClasses --onlyIncludeSpecified
```

and get

<details>
<summary>usage-by-api.json</summary>

```json
{
  "methods": {},
  "classes": {
    "org/acegisecurity/AccountExpiredException": ["crowd2"],
    "org/springframework/web/util/HtmlUtils": ["restricted-register"],
    "org/acegisecurity/context/SecurityContextImpl": [
      "blueocean-jwt",
      "jwt-support"
    ],
    "org/acegisecurity/userdetails/User": [
      "active-directory",
      "assembla-auth",
      "backlog",
      "cas-plugin",
      "coding-webhook",
      "github-oauth",
      "gitlab-oauth",
      "keycloak",
      "mock-security-realm",
      "openid",
      "pam-auth",
      "pwauth",
      "script-realm",
      "url-auth-sso",
      "wso2id-oauth"
    ],
    "org/acegisecurity/ldap/LdapDataAccessException": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/springframework/web/context/support/XmlWebApplicationContext": ["crowd"],
    "org/springframework/beans/factory/InitializingBean": [
      "cas-plugin",
      "reverse-proxy-auth-plugin"
    ],
    "org/acegisecurity/GrantedAuthorityImpl": [
      "active-directory",
      "assembla-auth",
      "azure-ad",
      "bitbucket-oauth",
      "cas-plugin",
      "crowd2",
      "github-oauth",
      "gitlab-oauth",
      "keycloak",
      "ldap",
      "mock-security-realm",
      "oic-auth",
      "openid",
      "pam-auth",
      "pwauth",
      "reverse-proxy-auth-plugin",
      "script-realm",
      "tuleap-oauth"
    ],
    "org/springframework/beans/BeanUtils": ["nsiqcollector"],
    "org/acegisecurity/LockedException": ["cas-plugin"],
    "org/acegisecurity/GrantedAuthority": [
      "active-directory",
      "azure-ad",
      "crowd2",
      "job-restrictions",
      "ldap",
      "oic-auth",
      "pipeline-input-step",
      "promoted-builds",
      "reverse-proxy-auth-plugin",
      "role-strategy",
      "saml"
    ],
    "org/springframework/util/Assert": [
      "azure-commons",
      "cas-plugin",
      "hp-operations-orchestration-automation-execution-plugin",
      "instant-messaging",
      "reverse-proxy-auth-plugin",
      "skype-notifier"
    ],
    "org/springframework/context/support/MessageSourceAccessor": ["reverse-proxy-auth-plugin"],
    "org/acegisecurity/userdetails/UsernameNotFoundException": [
      "active-directory",
      "assembla-auth",
      "azure-ad",
      "backlog",
      "bitbucket-oauth",
      "coding-webhook",
      "crowd2",
      "github-oauth",
      "gitlab-oauth",
      "ldap",
      "mock-security-realm",
      "oic-auth",
      "pam-auth",
      "pwauth",
      "redmine",
      "reverse-proxy-auth-plugin",
      "saml",
      "script-realm",
      "tuleap-oauth",
      "wwpass-plugin"
    ],
    "org/acegisecurity/ldap/LdapTemplate": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/springframework/beans/factory/DisposableBean": ["jira"],
    "org/springframework/dao/DataAccessException": [
      "kerberos-sso",
      "reverse-proxy-auth-plugin"
    ],
    "org/acegisecurity/providers/ldap/LdapAuthoritiesPopulator": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/springframework/util/ReflectionUtils": [
      "DotCi",
      "ez-templates"
    ],
    "org/acegisecurity/AuthenticationManager": [
      "assembla-auth",
      "authorize-project",
      "azure-ad",
      "bitbucket-oauth",
      "cas-plugin",
      "coding-webhook",
      "crowd2",
      "DotCi",
      "github-oauth",
      "gitlab-oauth",
      "google-login",
      "ibm-continuous-release",
      "keycloak",
      "ldap",
      "oic-auth",
      "saml",
      "skype-notifier",
      "tuleap-oauth",
      "urbancode-velocity",
      "url-auth-sso",
      "wso2id-oauth",
      "wwpass-plugin"
    ],
    "org/acegisecurity/ui/rememberme/RememberMeServices": ["crowd2"],
    "org/acegisecurity/AccessDeniedException": [
      "authorize-project",
      "build-failure-analyzer",
      "build-token-root",
      "cloudbees-folder",
      "depgraph-view",
      "docker-traceability",
      "jobtemplates",
      "metrics",
      "node-sharing-orchestrator",
      "ownership",
      "pipeline-model-definition",
      "pubsub-light",
      "slave-squatter",
      "svnmerge",
      "workflow-cps"
    ],
    "org/springframework/dao/DataAccessResourceFailureException": ["reverse-proxy-auth-plugin"],
    "org/acegisecurity/userdetails/UserDetailsService": [
      "active-directory",
      "assembla-auth",
      "azure-ad",
      "bitbucket-oauth",
      "coding-webhook",
      "crowd",
      "crowd2",
      "github-oauth",
      "gitlab-oauth",
      "ldap",
      "oic-auth",
      "pwauth",
      "reverse-proxy-auth-plugin",
      "url-auth-sso"
    ],
    "org/springframework/context/ApplicationListener": ["cas-plugin"],
    "org/acegisecurity/InsufficientAuthenticationException": ["crowd2"],
    "org/acegisecurity/context/SecurityContextHolder": [
      "alauda-devops-sync",
      "assembla-auth",
      "azure-ad",
      "backlog",
      "backup",
      "bitbucket",
      "bitbucket-oauth",
      "blueocean-bitbucket-pipeline",
      "blueocean-github-pipeline",
      "blueocean-jwt",
      "build-token-root",
      "buildresult-trigger",
      "cas-plugin",
      "coding-webhook",
      "credentials",
      "crowd2",
      "deploydb",
      "docker-slaves",
      "dockerhub-notification",
      "DotCi",
      "elasticbox",
      "embeddable-build-status",
      "extended-choice-parameter",
      "feature-branch-notifier",
      "gearman-plugin",
      "generic-webhook-trigger",
      "gerrit-code-review",
      "ghprb",
      "gitbucket",
      "github-oauth",
      "github-pullrequest",
      "gitlab-oauth",
      "gogs-webhook",
      "google-login",
      "ibm-continuous-release",
      "jclouds-jenkins",
      "job-fan-in",
      "jobcopy-builder",
      "jwt-support",
      "kerberos-sso",
      "keycloak",
      "metrics",
      "multibranch-scan-webhook-trigger",
      "NegotiateSSO",
      "oic-auth",
      "openid",
      "openshift-login",
      "openshift-sync",
      "ownership",
      "periodicbackup",
      "PrioritySorter",
      "project-inheritance",
      "promoted-builds",
      "rabbitmq-consumer",
      "random-job-builder",
      "reverse-proxy-auth-plugin",
      "saml",
      "scm-api",
      "script-security",
      "security-inspector",
      "seed",
      "subversion",
      "teamconcert-git",
      "tfs",
      "thinBackup",
      "throttle-concurrents",
      "tuleap-oauth",
      "urbancode-velocity",
      "url-auth-sso",
      "windows-azure-storage",
      "wso2id-oauth",
      "wwpass-plugin",
      "xpdev",
      "zanata"
    ],
    "org/acegisecurity/acls/sid/PrincipalSid": [
      "folder-auth",
      "role-strategy",
      "ssh2easy"
    ],
    "org/springframework/web/context/WebApplicationContext": ["cas-plugin"],
    "org/springframework/util/FileCopyUtils": ["fabric-beta-publisher"],
    "org/springframework/core/io/ClassPathResource": ["covcomplplot"],
    "org/springframework/util/AntPathMatcher": [
      "ca-service-virtualization",
      "coding-webhook",
      "credentials",
      "scm-sync-configuration",
      "windows-azure-storage"
    ],
    "org/acegisecurity/AuthenticationServiceException": [
      "active-directory",
      "cas-plugin",
      "crowd2",
      "reverse-proxy-auth-plugin",
      "script-realm"
    ],
    "org/acegisecurity/ldap/LdapEntryMapper": ["ldap"],
    "org/acegisecurity/CredentialsExpiredException": ["crowd2"],
    "org/acegisecurity/providers/UsernamePasswordAuthenticationToken": [
      "active-directory",
      "authorize-project",
      "cas-plugin",
      "coding-webhook",
      "copyartifact",
      "credentials",
      "github-oauth",
      "gitlab-oauth",
      "google-login",
      "hp-application-automation-tools-plugin",
      "ibm-continuous-release",
      "kerberos-sso",
      "ldap",
      "NegotiateSSO",
      "oic-auth",
      "openid",
      "openshift-login",
      "perfectomobile",
      "pwauth",
      "redmine",
      "reverse-proxy-auth-plugin",
      "s3",
      "skype-notifier",
      "urbancode-velocity",
      "wso2id-oauth"
    ],
    "org/acegisecurity/Authentication": [
      "active-directory",
      "assembla-auth",
      "atlassian-bitbucket-server-integration",
      "authorize-project",
      "azure-ad",
      "block-same-builds",
      "blueocean-jwt",
      "blueocean-pipeline-api-impl",
      "blueocean-pipeline-scm-api",
      "blueocean-rest-impl",
      "build-failure-analyzer",
      "claim",
      "coding-webhook",
      "concurrent-login-plugin",
      "copyartifact",
      "createjobadvanced",
      "credentials",
      "crowd2",
      "DotCi",
      "favorite",
      "gerrit-code-review",
      "gerrit-trigger",
      "git-server",
      "github-oauth",
      "gitlab-oauth",
      "greenballs",
      "hp-application-automation-tools-plugin",
      "job-fan-in",
      "jobConfigHistory",
      "jwt-support",
      "kerberos-sso",
      "ldap",
      "m2release",
      "monitoring",
      "NegotiateSSO",
      "parameterized-trigger",
      "pipeline-input-step",
      "pipeline-maven",
      "project-inheritance",
      "promoted-builds",
      "pwauth",
      "remote-terminal-access",
      "reverse-proxy-auth-plugin",
      "saml",
      "script-security",
      "scriptler",
      "splunk-devops",
      "statistics-gatherer",
      "strict-crumb-issuer",
      "sumologic-publisher",
      "support-core",
      "teamconcert-git",
      "tuleap-oauth",
      "typetalk",
      "view-job-filters",
      "windows-azure-storage",
      "workflow-cps",
      "workflow-durable-task-step",
      "workflow-job",
      "wwpass-plugin"
    ],
    "org/springframework/util/StopWatch": [
      "qualityclouds",
      "telerik-appbuilder-plugin"
    ],
    "org/springframework/dao/DataRetrievalFailureException": [
      "coding-webhook",
      "crowd2",
      "github-oauth",
      "gitlab-oauth",
      "wso2id-oauth"
    ],
    "org/springframework/context/MessageSourceAware": ["reverse-proxy-auth-plugin"],
    "org/springframework/util/CollectionUtils": [
      "lambdatest-automation",
      "whitesource"
    ],
    "org/springframework/util/StringUtils": [
      "cas-plugin",
      "dbforge-devops-automation-for-sqlserver",
      "ec2-deployment-dashboard",
      "openstack-cloud",
      "qualityclouds",
      "reverse-proxy-auth-plugin",
      "selenium"
    ],
    "org/acegisecurity/ldap/LdapUserSearch": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/acegisecurity/providers/ldap/LdapAuthenticationProvider": ["ldap"],
    "org/acegisecurity/userdetails/ldap/LdapUserDetails": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/acegisecurity/DisabledException": ["cas-plugin"],
    "org/acegisecurity/acls/NotFoundException": ["artifactory"],
    "org/acegisecurity/ldap/LdapCallback": ["ldap"],
    "org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor": ["paaslane-estimate"],
    "org/acegisecurity/providers/AbstractAuthenticationToken": [
      "assembla-auth",
      "bitbucket-oauth",
      "blueocean-jwt",
      "cas-plugin",
      "coding-webhook",
      "crowd2",
      "github-oauth",
      "gitlab-oauth",
      "jwt-support",
      "keycloak",
      "saml",
      "tuleap-oauth",
      "url-auth-sso",
      "wso2id-oauth",
      "wwpass-plugin"
    ],
    "org/acegisecurity/AuthenticationException": [
      "active-directory",
      "gitlab-oauth",
      "pwauth",
      "redmine"
    ],
    "org/acegisecurity/providers/ldap/populator/DefaultLdapAuthoritiesPopulator": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/springframework/dao/InvalidDataAccessApiUsageException": ["reverse-proxy-auth-plugin"],
    "org/springframework/util/ObjectUtils": ["ec2-fleet"],
    "org/acegisecurity/BadCredentialsException": [
      "active-directory",
      "assembla-auth",
      "azure-ad",
      "backlog",
      "bitbucket-oauth",
      "cas-plugin",
      "coding-webhook",
      "crowd2",
      "delivery-pipeline-plugin",
      "github-oauth",
      "gitlab-oauth",
      "google-login",
      "keycloak",
      "mock-security-realm",
      "oic-auth",
      "openid",
      "openshift-login",
      "pam-auth",
      "pwauth",
      "reverse-proxy-auth-plugin",
      "saml",
      "script-realm",
      "tuleap-oauth",
      "wso2id-oauth",
      "wwpass-plugin"
    ],
    "org/acegisecurity/AcegiMessageSource": ["reverse-proxy-auth-plugin"],
    "org/acegisecurity/context/SecurityContext": [
      "assembla-auth",
      "azure-ad",
      "backup",
      "bitbucket-oauth",
      "blueocean-jwt",
      "cas-plugin",
      "coding-webhook",
      "crowd2",
      "DotCi",
      "elasticbox",
      "extended-choice-parameter",
      "ghprb",
      "gitbucket",
      "github-oauth",
      "gitlab-oauth",
      "google-login",
      "ibm-continuous-release",
      "jclouds-jenkins",
      "jwt-support",
      "kerberos-sso",
      "keycloak",
      "NegotiateSSO",
      "oic-auth",
      "openid",
      "openshift-login",
      "periodicbackup",
      "promoted-builds",
      "reverse-proxy-auth-plugin",
      "saml",
      "subversion",
      "teamconcert-git",
      "thinBackup",
      "tuleap-oauth",
      "urbancode-velocity",
      "url-auth-sso",
      "wso2id-oauth",
      "wwpass-plugin",
      "xpdev"
    ],
    "org/acegisecurity/userdetails/ldap/LdapUserDetailsImpl$Essence": [
      "ldap",
      "reverse-proxy-auth-plugin"
    ],
    "org/acegisecurity/userdetails/UserDetails": [
      "active-directory",
      "assembla-auth",
      "azure-ad",
      "bitbucket-oauth",
      "blueocean-jwt",
      "coding-webhook",
      "crowd2",
      "datadog",
      "github-oauth",
      "ibm-continuous-release",
      "job-restrictions",
      "jwt-support",
      "kerberos-sso",
      "mock-security-realm",
      "NegotiateSSO",
      "oic-auth",
      "openshift-login",
      "redmine",
      "reverse-proxy-auth-plugin",
      "role-strategy",
      "saml",
      "splunk-devops",
      "sumologic-publisher",
      "tuleap-oauth",
      "urbancode-velocity",
      "url-auth-sso",
      "wwpass-plugin"
    ],
    "org/springframework/web/filter/GenericFilterBean": ["cas-plugin"],
    "org/acegisecurity/providers/dao/AbstractUserDetailsAuthenticationProvider": [
      "active-directory",
      "redmine",
      "reverse-proxy-auth-plugin"
    ],
    "org/springframework/util/ClassUtils": ["pipeline-maven"]
  },
  "fields": {}
}
```
</details>

**Comment by Wadeck** [comment]
@jglick your output does not seem to catch the same stuff, e.g. AccessDeniedException, you got 15 entries while I got 46.

**Comment by Wadeck** [comment]
@jglick your output does not seem to catch the same stuff, e.g. AccessDeniedException, you got 15 entries while I got 46.

**Comment by jglick** [comment]
https://github.com/jenkinsci/branch-api-plugin/blob/6a3cce06c8f45185e094c6879581532fc6bb5cdf/src/main/java/jenkins/branch/OrganizationFolder.java#L278 for example. Seems like a bug in the tool? I barely follow your edits so I am not sure what all you did that might account for the different behavior.

**Comment by jglick** [comment]
https://github.com/jenkinsci/junit-plugin/blob/bab34bcc96154a494f8c371953efe06d45813f67/src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java#L175 is a perhaps more interesting example.

Did you rewrite class scanner code to deal differently with `Throwable` subtypes or something?

**Comment by Wadeck** [comment]
> Did you rewrite class scanner code to deal differently with Throwable subtypes or something?

I rewrite parts of the tool to ensure most (not all) of the possible class name it encounters are checked (and their super type) against acegi package name. The catch part was one of the "difficult" aspect to find a way to get :) 

For the Throws => https://github.com/jenkins-infra/usage-in-plugins/pull/15/files?file-filters%5B%5D=.java#diff-bba615b046386d2cf10b1e24cb04997dR75

For the catch => https://github.com/jenkins-infra/usage-in-plugins/pull/15/files?file-filters%5B%5D=.java#diff-e73c67b379c664efd4c455c348f7b5e0R420 (this one was particularly interesting)

**Comment by jglick** [comment]
In other words, you fixed at least two serious bugs in this tool, alongside the stated purpose of looking for Acegi Security classes. Could you file a mergeable PR that just fixes those bugs please? Then this could be closed, as `--additionalClasses … --onlyIncludeSpecified` would work generally.

**Comment by jglick** [comment]
BTW I think you missed `instanceof`: https://github.com/jenkinsci/matrix-auth-plugin/blob/89cf0da7f36e657e727f84b2a3bd996af9030bbe/src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java#L138

**Comment by jglick** [comment]
Simpler would be to just get all of the `Type`s out of the constant pool using `ClassReader.readConst`, but I have not yet been able to get this to work: gives me `ArrayIndexOutOfBoundsException` which I have been unable to track down without debugging information.

**Comment by Wadeck** [comment]
Yeah the `instanceof` seems to be the explanation for the difference. Your approach does not really care about the details about where the classes are used and thus is a lot simpler (if we omit the byte computation).

This PR was not meant to be merged and as it's a lot more complicated than the proposal from Jesse, I just close it.

**Pull request closed without merging**
